#!/usr/bin/env python
# encoding: utf-8

"""
Here's the list of words used to search the REF case studies
"""

SEARCH_TERM_LIST = [
    'big data',
    'computation',
    'computational',
    'computed',
    'computer',
    'data analysis',
    'data base',
    'database',
    'excel',
    'fortran',
    'geographic information science',
    'geographic information systems',
    'gis',
    'git',
    'github',
    'graphics',
    'high performance computing',
    'hpc',
    'imagej',
    'implemented in',
    'in silico',
    'matlab',
    'model',
    'modeling',
    'modelling',
    'nvivo',
    'open source',
    'open-source',
    'python',
    'quantitative',
    'r language',
    'in r',
    'simulated',
    'simulation',
    'software',
    'spss',
    'stata',
    'supercomputing',
    'visualisation',
    'visualization',
    'Rcpp',
    'ggplot2',
    'plyr',
    'stringr',
    'reshape2',
    'RColorBrewer'
    ]